/*
 * TIMER_Program.c
 *
 *  Created on: Nov 18, 2021
 *      Author: gerges
 */

#include"..\..\LIB\LSTD_TYPES.h"
#include"..\..\LIB\LBIT_MATH.h"
#include"TIMER_Private.h"
#include"TIMER_Config.h"
static u8 Count = 0;
static u32 T1 = 0;
static u32 T2 = 0;
static u32 T3 = 0;
static u8 Flag = 0;
void (*TIMER0_CallBack)(void);
void (*TIMER1_CallBack)(void);
void (*TIMER2_CallBack)(void);
/*Timer0 Initialization*/
void TIMER0_VidInit(void)
{
	/*Select the suitable Prescaler */
	TCCR0&=0xF8;
	TCCR0|=TIMER0_SET_PRESCALER;
	/*Mode Select*/
#if TIMER0_SET_MODE == TIMER0_NORMAL_MODE
	CLR_BIT(TCCR0,6);
	CLR_BIT(TCCR0,3);
	/*Timer Overflow Interrupt Enable*/
	SET_BIT(TIMSK,0);

#elif TIMER0_SET_MODE == TIMER0_CTC_MODE
	CLR_BIT(TCCR0,6);
	SET_BIT(TCCR0,3);
#if TIMER0_SET_CTC_INTERRUPT == TIMER0_CTC_INTERRUPT_ENABLED
	SET_BIT(TIMSK,1);
#elif TIMER0_SET_CTC_INTERRUPT == TIMER0_CTC_INTERRUPT_DISABLED
	CLR_BIT(TIMSK,1);
#else
#error "TIMER0 CTC Interrupt Mode is not valid..."
#endif
#if TIMER0_SET_OC0_PIN_MODE == TIMER0_OC0_PIN_DISCONNECTED
	CLR_BIT(TCCR0,5);
	CLR_BIT(TCCR0,4);
#elif TIMER0_SET_OC0_PIN_MODE == TIMER0_OC0_PIN_TOGGLE
	CLR_BIT(TCCR0,5);
	SET_BIT(TCCR0,4);
#elif TIMER0_SET_OC0_PIN_MODE == TIMER0_OC0_PIN_SET
	SET_BIT(TCCR0,5);
	SET_BIT(TCCR0,4);
#elif TIMER0_SET_OC0_PIN_MODE == TIMER0_OC0_PIN_CLR
	SET_BIT(TCCR0,5);
	CLR_BIT(TCCR0,4);
#else
#error "TIMER0 CTC OC0 Mode is not valid..."
#endif
#elif TIMER0_SET_MODE == TIMER0_PHASECORRECT_PWM_MODE
	SET_BIT(TCCR0,6);
	CLR_BIT(TCCR0,3);
	/*select phase correct mode */
#if TIMER0_SET_PWM_MODE == TIMER0_NUN_INVERTING_PWM
	   SET_BIT(TCCR0,1);
		CLR_BIT(TCCR0,0);
		CLR_BIT(TCCR0,4);
		SET_BIT(TCCR0,5);

#elif TIMER0_SET_PWM_MODE == TIMER0_INVERTING_PWM
	    SET_BIT(TCCR0,5);
		SET_BIT(TCCR0,4);

#else
#error "TIMER0 PWM Mode is not valid..."
#endif
#elif TIMER0_SET_MODE == TIMER0_FAST_PWM_MODE
	SET_BIT(TCCR0,6);
	SET_BIT(TCCR0,3);
	/*select TIMER0 FAST PWM_MODE mode */
#if TIMER0_SET_PWM_MODE == TIMER0_NUN_INVERTING_PWM
	        SET_BIT(TCCR0,1);
			CLR_BIT(TCCR0,0);
			CLR_BIT(TCCR0,4);
			SET_BIT(TCCR0,5);
#elif TIMER0_SET_PWM_MODE == TIMER0_INVERTING_PWM
			SET_BIT(TCCR0,5);
			SET_BIT(TCCR0,4);


#else
#error "TIMER0 PWM Mode is not valid..."
#endif
#else
#error "TIMER0 Mode is not valid..."
#endif

}
/*Set Preload Function*/
void TIMER0_VidSetPreload(u8 Copy_u8Preload)
{
	TCNT0=Copy_u8Preload;
}
/*Set CTC Value Function*/
void TIMER0_VidSetCTCValue(u8 Copy_u8CTCValue)
{
	OCR0=Copy_u8CTCValue;
}
void TIMER0_VidOVF_SetCallBack(void(*Copy_VidCallBack)(void))
{
	TIMER0_CallBack=Copy_VidCallBack;
}
void TIMER0_VidCTC_SetCallBack(void(*Copy_VidCallBack)(void))
{
	TIMER0_CallBack=Copy_VidCallBack;
}
void __vector_11(void)   __attribute__((signal));
void __vector_11(void)
{
	TIMER0_CallBack();
}
void __vector_10(void)   __attribute__((signal));
void __vector_10(void)
{
	TIMER0_CallBack();
}
void TIMER1_VidInit(void)
{
	/*Select the suitable Prescaler */
		TCCR1B&=0xF8;
		TCCR1B|=TIMER1_SET_PRESCALER;

		/*Mode Select*/
#if TIMER1_SET_MODE == TIMER1_NORMAL_MODE
	CLR_BIT(TCCR1A,0);
	CLR_BIT(TCCR1A,1);
	CLR_BIT(TCCR1B,3);
	CLR_BIT(TCCR1B,4);
	/*Timer Overflow Interrupt Enable*/
	SET_BIT(TIMSK,2);

#elif TIMER1_SET_MODE == TIMER1_PHASECORRECT_PWM_MODE_8BITS
	   SET_BIT(TCCR1A,0);
	   CLR_BIT(TCCR1A,1);
	   CLR_BIT(TCCR1B,3);
	   CLR_BIT(TCCR1B,4);
#if CHANNEL_MODE == CHANNELA
#if TIMER1_SET_OC1A_OR_OC1B_PIN_MODE == TIMER1_OC1A_OR_OC1B_PIN_DISCONNECTED
	   CLR_BIT(TCCR1A,6);
	   CLR_BIT(TCCR1A,7);
#elif TIMER1_SET_OC1A_OR_OC1B_PIN_MODE ==  TIMER1_OC1A_OR_OC1B_PIN_TOGGLE
	   SET_BIT(TCCR1A,6);
	   CLR_BIT(TCCR1A,7);
#elif TIMER1_SET_OC1A_OR_OC1B_PIN_MODE ==  TIMER1_OC1A_OR_OC1B_PIN_CLR
	   CLR_BIT(TCCR1A,6);
	   SET_BIT(TCCR1A,7);
#elif TIMER1_SET_OC1A_OR_OC1B_PIN_MODE ==  TIMER1_OC1A_OR_OC1B_PIN_SET
	   SET_BIT(TCCR1A,6);
	   SET_BIT(TCCR1A,7);
#else
#error "TIMER1 CTC OC1A Mode is not valid.. "
#endif
#elif CHANNEL_MODE == CHANNELB
#if TIMER1_SET_OC1A_OR_OC1B_PIN_MODE == TIMER1_OC1A_OR_OC1B_PIN_DISCONNECTED
	   CLR_BIT(TCCR1A,4);
	   CLR_BIT(TCCR1A,5);
#elif TIMER1_SET_OC1A_OR_OC1B_PIN_MODE ==  TIMER1_OC1A_OR_OC1B_PIN_TOGGLE
	   SET_BIT(TCCR1A,4);
	   CLR_BIT(TCCR1A,5);
#elif TIMER1_SET_OC1A_OR_OC1B_PIN_MODE ==  TIMER1_OC1A_OR_OC1B_PIN_CLR
	   CLR_BIT(TCCR1A,4);
	   SET_BIT(TCCR1A,5);
#elif TIMER1_SET_OC1A_OR_OC1B_PIN_MODE ==  TIMER1_OC1A_OR_OC1B_PIN_SET
	   SET_BIT(TCCR1A,4);
	   SET_BIT(TCCR1A,5);
#else
#error "TIMER1 CTC OC1B Mode is not valid.. "
#endif
#else
#error "TIMER1 Channel Mode is not valid.. "
#endif

#elif TIMER1_SET_MODE ==  TIMER1_PHASECORRECT_PWM_MODE_9BITS
	 CLR_BIT(TCCR1A,0);
	 SET_BIT(TCCR1A,1);
	 CLR_BIT(TCCR1B,3);
	 CLR_BIT(TCCR1B,4);
#if CHANNEL_MODE == CHANNELA
#if TIMER1_SET_OC1A_OR_OC1B_PIN_MODE == TIMER1_OC1A_OR_OC1B_PIN_DISCONNECTED
	   CLR_BIT(TCCR1A,6);
	   CLR_BIT(TCCR1A,7);
#elif TIMER1_SET_OC1A_OR_OC1B_PIN_MODE ==  TIMER1_OC1A_OR_OC1B_PIN_TOGGLE
	   SET_BIT(TCCR1A,6);
	   CLR_BIT(TCCR1A,7);
#elif TIMER1_SET_OC1A_OR_OC1B_PIN_MODE ==  TIMER1_OC1A_OR_OC1B_PIN_CLR
	   CLR_BIT(TCCR1A,6);
	   SET_BIT(TCCR1A,7);
#elif TIMER1_SET_OC1A_OR_OC1B_PIN_MODE ==  TIMER1_OC1A_OR_OC1B_PIN_SET
	   SET_BIT(TCCR1A,6);
	   SET_BIT(TCCR1A,7);
#else
#error "TIMER1 CTC OC1A Mode is not valid.. "
#endif
#elif CHANNEL_MODE == CHANNELB
#if TIMER1_SET_OC1A_OR_OC1B_PIN_MODE == TIMER1_OC1A_OR_OC1B_PIN_DISCONNECTED
	   CLR_BIT(TCCR1A,4);
	   CLR_BIT(TCCR1A,5);
#elif TIMER1_SET_OC1A_OR_OC1B_PIN_MODE ==  TIMER1_OC1A_OR_OC1B_PIN_TOGGLE
	   SET_BIT(TCCR1A,4);
	   CLR_BIT(TCCR1A,5);
#elif TIMER1_SET_OC1A_OR_OC1B_PIN_MODE ==  TIMER1_OC1A_OR_OC1B_PIN_CLR
	   CLR_BIT(TCCR1A,4);
	   SET_BIT(TCCR1A,5);
#elif TIMER1_SET_OC1A_OR_OC1B_PIN_MODE ==  TIMER1_OC1A_OR_OC1B_PIN_SET
	   SET_BIT(TCCR1A,4);
	   SET_BIT(TCCR1A,5);
#else
#error "TIMER1 CTC OC1B Mode is not valid.. "
#endif
#else
#error "TIMER1 Channel Mode is not valid.. "
#endif
#elif TIMER1_SET_MODE == TIMER1_PHASECORRECT_PWM_MODE_10BITS
	 SET_BIT(TCCR1A,0);
	 SET_BIT(TCCR1A,1);
	 CLR_BIT(TCCR1B,3);
	 CLR_BIT(TCCR1B,4);
#if CHANNEL_MODE == CHANNELA
#if TIMER1_SET_OC1A_OR_OC1B_PIN_MODE == TIMER1_OC1A_OR_OC1B_PIN_DISCONNECTED
	   CLR_BIT(TCCR1A,6);
	   CLR_BIT(TCCR1A,7);
#elif TIMER1_SET_OC1A_OR_OC1B_PIN_MODE ==  TIMER1_OC1A_OR_OC1B_PIN_TOGGLE
	   SET_BIT(TCCR1A,6);
	   CLR_BIT(TCCR1A,7);
#elif TIMER1_SET_OC1A_OR_OC1B_PIN_MODE ==  TIMER1_OC1A_OR_OC1B_PIN_CLR
	   CLR_BIT(TCCR1A,6);
	   SET_BIT(TCCR1A,7);
#elif TIMER1_SET_OC1A_OR_OC1B_PIN_MODE ==  TIMER1_OC1A_OR_OC1B_PIN_SET
	   SET_BIT(TCCR1A,6);
	   SET_BIT(TCCR1A,7);
#else
#error "TIMER1 CTC OC1A Mode is not valid.. "
#endif

#elif CHANNEL_MODE == CHANNELB
#if TIMER1_SET_OC1A_OR_OC1B_PIN_MODE == TIMER1_OC1A_OR_OC1B_PIN_DISCONNECTED
	   CLR_BIT(TCCR1A,4);
	   CLR_BIT(TCCR1A,5);
#elif TIMER1_SET_OC1A_OR_OC1B_PIN_MODE ==  TIMER1_OC1A_OR_OC1B_PIN_TOGGLE
	   SET_BIT(TCCR1A,4);
	   CLR_BIT(TCCR1A,5);
#elif TIMER1_SET_OC1A_OR_OC1B_PIN_MODE ==  TIMER1_OC1A_OR_OC1B_PIN_CLR
	   CLR_BIT(TCCR1A,4);
	   SET_BIT(TCCR1A,5);
#elif TIMER1_SET_OC1A_OR_OC1B_PIN_MODE ==  TIMER1_OC1A_OR_OC1B_PIN_SET
	   SET_BIT(TCCR1A,4);
	   SET_BIT(TCCR1A,5);
#else
#error "TIMER1 CTC OC1B Mode is not valid.. "
#endif
#else
#error "TIMER1 Channel Mode is not valid.. "
#endif
#elif TIMER1_SET_MODE == TIMER1_CTC_MODE_WITH_OCR1A
	 CLR_BIT(TCCR1A,0);
	 CLR_BIT(TCCR1A,1);
	 SET_BIT(TCCR1B,3);
	 CLR_BIT(TCCR1B,4);
#if CHANNEL_MODE == CHANNELA
#if TIMER1_SET_CTC_INTERRUPT == TIMER1_CTC_INTERRUPT_ENABLED
	SET_BIT(TIMSK,4);
#elif TIMER1_SET_CTC_INTERRUPT == TIMER1_CTC_INTERRUPT_DISABLED
	CLR_BIT(TIMSK,4);
#else
#error "TIMER1 CTC Interrupt Mode is not valid..."
#endif
#if TIMER1_SET_OC1A_OR_OC1B_PIN_MODE == TIMER1_OC1A_OR_OC1B_PIN_DISCONNECTED
	   CLR_BIT(TCCR1A,6);
	   CLR_BIT(TCCR1A,7);
#elif TIMER1_SET_OC1A_OR_OC1B_PIN_MODE ==  TIMER1_OC1A_OR_OC1B_PIN_TOGGLE
	   SET_BIT(TCCR1A,6);
	   CLR_BIT(TCCR1A,7);
#elif TIMER1_SET_OC1A_OR_OC1B_PIN_MODE ==  TIMER1_OC1A_OR_OC1B_PIN_CLR
	   CLR_BIT(TCCR1A,6);
	   SET_BIT(TCCR1A,7);
#elif TIMER1_SET_OC1A_OR_OC1B_PIN_MODE ==  TIMER1_OC1A_OR_OC1B_PIN_SET
	   SET_BIT(TCCR1A,6);
	   SET_BIT(TCCR1A,7);
#else
#error "TIMER1 CTC OC1A Mode is not valid.. "
#endif

#elif CHANNEL_MODE == CHANNELB
#if TIMER1_SET_CTC_INTERRUPT == TIMER1_CTC_INTERRUPT_ENABLED
	SET_BIT(TIMSK,3);
#elif TIMER1_SET_CTC_INTERRUPT == TIMER1_CTC_INTERRUPT_DISABLED
	CLR_BIT(TIMSK,3);
#else
#error "TIMER1 CTC Interrupt Mode is not valid..."
#endif
#if TIMER1_SET_OC1A_OR_OC1B_PIN_MODE == TIMER1_OC1A_OR_OC1B_PIN_DISCONNECTED
	   CLR_BIT(TCCR1A,4);
	   CLR_BIT(TCCR1A,5);
#elif TIMER1_SET_OC1A_OR_OC1B_PIN_MODE ==  TIMER1_OC1A_OR_OC1B_PIN_TOGGLE
	   SET_BIT(TCCR1A,4);
	   CLR_BIT(TCCR1A,5);
#elif TIMER1_SET_OC1A_OR_OC1B_PIN_MODE ==  TIMER1_OC1A_OR_OC1B_PIN_CLR
	   CLR_BIT(TCCR1A,4);
	   SET_BIT(TCCR1A,5);
#elif TIMER1_SET_OC1A_OR_OC1B_PIN_MODE ==  TIMER1_OC1A_OR_OC1B_PIN_SET
	   SET_BIT(TCCR1A,4);
	   SET_BIT(TCCR1A,5);
#else
#error "TIMER1 CTC OC1B Mode is not valid.. "
#endif
#else
#error "TIMER1 Channel Mode is not valid.. "
#endif
#elif TIMER1_SET_MODE == TIMER1_FAST_PWM_MODE_8BITS
	  SET_BIT(TCCR1A,0);
	  CLR_BIT(TCCR1A,1);
	  SET_BIT(TCCR1B,3);
	  CLR_BIT(TCCR1B,4);
#if CHANNEL_MODE == CHANNELA
#if TIMER1_SET_OC1A_OR_OC1B_PIN_MODE == TIMER1_OC1A_OR_OC1B_PIN_DISCONNECTED
	   CLR_BIT(TCCR1A,6);
	   CLR_BIT(TCCR1A,7);
#elif TIMER1_SET_OC1A_OR_OC1B_PIN_MODE ==  TIMER1_OC1A_OR_OC1B_PIN_TOGGLE
	   SET_BIT(TCCR1A,6);
	   CLR_BIT(TCCR1A,7);
#elif TIMER1_SET_OC1A_OR_OC1B_PIN_MODE ==  TIMER1_OC1A_OR_OC1B_PIN_CLR
	   CLR_BIT(TCCR1A,6);
	   SET_BIT(TCCR1A,7);
#elif TIMER1_SET_OC1A_OR_OC1B_PIN_MODE ==  TIMER1_OC1A_OR_OC1B_PIN_SET
	   SET_BIT(TCCR1A,6);
	   SET_BIT(TCCR1A,7);
#else
#error "TIMER1 CTC OC1A Mode is not valid.. "
#endif

#elif CHANNEL_MODE == CHANNELB
#if TIMER1_SET_OC1A_OR_OC1B_PIN_MODE == TIMER1_OC1A_OR_OC1B_PIN_DISCONNECTED
	   CLR_BIT(TCCR1A,4);
	   CLR_BIT(TCCR1A,5);
#elif TIMER1_SET_OC1A_OR_OC1B_PIN_MODE ==  TIMER1_OC1A_OR_OC1B_PIN_TOGGLE
	   SET_BIT(TCCR1A,4);
	   CLR_BIT(TCCR1A,5);
#elif TIMER1_SET_OC1A_OR_OC1B_PIN_MODE ==  TIMER1_OC1A_OR_OC1B_PIN_CLR
	   CLR_BIT(TCCR1A,4);
	   SET_BIT(TCCR1A,5);
#elif TIMER1_SET_OC1A_OR_OC1B_PIN_MODE ==  TIMER1_OC1A_OR_OC1B_PIN_SET
	   SET_BIT(TCCR1A,4);
	   SET_BIT(TCCR1A,5);
#else
#error "TIMER1 CTC OC1B Mode is not valid.. "
#endif
#else
#error "TIMER1 Channel Mode is not valid.. "
#endif
#elif TIMER1_SET_MODE == TIMER1_FAST_PWM_MODE_9BITS
	  CLR_BIT(TCCR1A,0);
	  SET_BIT(TCCR1A,1);
	  SET_BIT(TCCR1B,3);
	  CLR_BIT(TCCR1B,4);
#if CHANNEL_MODE == CHANNELA
#if TIMER1_SET_OC1A_OR_OC1B_PIN_MODE == TIMER1_OC1A_OR_OC1B_PIN_DISCONNECTED
	   CLR_BIT(TCCR1A,6);
	   CLR_BIT(TCCR1A,7);
#elif TIMER1_SET_OC1A_OR_OC1B_PIN_MODE ==  TIMER1_OC1A_OR_OC1B_PIN_TOGGLE
	   SET_BIT(TCCR1A,6);
	   CLR_BIT(TCCR1A,7);
#elif TIMER1_SET_OC1A_OR_OC1B_PIN_MODE ==  TIMER1_OC1A_OR_OC1B_PIN_CLR
	   CLR_BIT(TCCR1A,6);
	   SET_BIT(TCCR1A,7);
#elif TIMER1_SET_OC1A_OR_OC1B_PIN_MODE ==  TIMER1_OC1A_OR_OC1B_PIN_SET
	   SET_BIT(TCCR1A,6);
	   SET_BIT(TCCR1A,7);
#else
#error "TIMER1 CTC OC1A Mode is not valid.. "
#endif
#elif CHANNEL_MODE == CHANNELB
#if TIMER1_SET_OC1A_OR_OC1B_PIN_MODE == TIMER1_OC1A_OR_OC1B_PIN_DISCONNECTED
	   CLR_BIT(TCCR1A,4);
	   CLR_BIT(TCCR1A,5);
#elif TIMER1_SET_OC1A_OR_OC1B_PIN_MODE ==  TIMER1_OC1A_OR_OC1B_PIN_TOGGLE
	   SET_BIT(TCCR1A,4);
	   CLR_BIT(TCCR1A,5);
#elif TIMER1_SET_OC1A_OR_OC1B_PIN_MODE ==  TIMER1_OC1A_OR_OC1B_PIN_CLR
	   CLR_BIT(TCCR1A,4);
	   SET_BIT(TCCR1A,5);
#elif TIMER1_SET_OC1A_OR_OC1B_PIN_MODE ==  TIMER1_OC1A_OR_OC1B_PIN_SET
	   SET_BIT(TCCR1A,4);
	   SET_BIT(TCCR1A,5);
#else
#error "TIMER1 CTC OC1B Mode is not valid.. "
#endif
#else
#error "TIMER1 Channel Mode is not valid.. "
#endif
#elif TIMER1_SET_MODE == TIMER1_FAST_PWM_MODE_10BITS
	  SET_BIT(TCCR1A,0);
	  SET_BIT(TCCR1A,1);
	  SET_BIT(TCCR1B,3);
	  CLR_BIT(TCCR1B,4);
#if CHANNEL_MODE == CHANNELA
#if TIMER1_SET_OC1A_OR_OC1B_PIN_MODE == TIMER1_OC1A_OR_OC1B_PIN_DISCONNECTED
	   CLR_BIT(TCCR1A,6);
	   CLR_BIT(TCCR1A,7);
#elif TIMER1_SET_OC1A_OR_OC1B_PIN_MODE ==  TIMER1_OC1A_OR_OC1B_PIN_TOGGLE
	   SET_BIT(TCCR1A,6);
	   CLR_BIT(TCCR1A,7);
#elif TIMER1_SET_OC1A_OR_OC1B_PIN_MODE ==  TIMER1_OC1A_OR_OC1B_PIN_CLR
	   CLR_BIT(TCCR1A,6);
	   SET_BIT(TCCR1A,7);
#elif TIMER1_SET_OC1A_OR_OC1B_PIN_MODE ==  TIMER1_OC1A_OR_OC1B_PIN_SET
	   SET_BIT(TCCR1A,6);
	   SET_BIT(TCCR1A,7);
#else
#error "TIMER1 CTC OC1A Mode is not valid.. "
#endif
#elif CHANNEL_MODE == CHANNELB
#if TIMER1_SET_OC1A_OR_OC1B_PIN_MODE == TIMER1_OC1A_OR_OC1B_PIN_DISCONNECTED
	   CLR_BIT(TCCR1A,4);
	   CLR_BIT(TCCR1A,5);
#elif TIMER1_SET_OC1A_OR_OC1B_PIN_MODE ==  TIMER1_OC1A_OR_OC1B_PIN_TOGGLE
	   SET_BIT(TCCR1A,4);
	   CLR_BIT(TCCR1A,5);
#elif TIMER1_SET_OC1A_OR_OC1B_PIN_MODE ==  TIMER1_OC1A_OR_OC1B_PIN_CLR
	   CLR_BIT(TCCR1A,4);
	   SET_BIT(TCCR1A,5);
#elif TIMER1_SET_OC1A_OR_OC1B_PIN_MODE ==  TIMER1_OC1A_OR_OC1B_PIN_SET
	   SET_BIT(TCCR1A,4);
	   SET_BIT(TCCR1A,5);
#else
#error "TIMER1 CTC OC1B Mode is not valid.. "
#endif
#else
#error "TIMER1 Channel Mode is not valid.. "
#endif

#elif TIMER1_SET_MODE == TIMER1_PWM_PHASE_AND_FREQUANCY_CORRECT_WITH_ICR1
	  CLR_BIT(TCCR1A,0);
	  CLR_BIT(TCCR1A,1);
	  CLR_BIT(TCCR1B,3);
	  SET_BIT(TCCR1B,4);
#if CHANNEL_MODE == CHANNELA
#if TIMER1_SET_OC1A_OR_OC1B_PIN_MODE == TIMER1_OC1A_OR_OC1B_PIN_DISCONNECTED
	   CLR_BIT(TCCR1A,6);
	   CLR_BIT(TCCR1A,7);
#elif TIMER1_SET_OC1A_OR_OC1B_PIN_MODE ==  TIMER1_OC1A_OR_OC1B_PIN_TOGGLE
	   SET_BIT(TCCR1A,6);
	   CLR_BIT(TCCR1A,7);
#elif TIMER1_SET_OC1A_OR_OC1B_PIN_MODE ==  TIMER1_OC1A_OR_OC1B_PIN_CLR
	   CLR_BIT(TCCR1A,6);
	   SET_BIT(TCCR1A,7);
#elif TIMER1_SET_OC1A_OR_OC1B_PIN_MODE ==  TIMER1_OC1A_OR_OC1B_PIN_SET
	   SET_BIT(TCCR1A,6);
	   SET_BIT(TCCR1A,7);
#else
#error "TIMER1 CTC OC1A Mode is not valid.. "
#endif
#elif CHANNEL_MODE == CHANNELB
#if TIMER1_SET_OC1A_OR_OC1B_PIN_MODE == TIMER1_OC1A_OR_OC1B_PIN_DISCONNECTED
	   CLR_BIT(TCCR1A,4);
	   CLR_BIT(TCCR1A,5);
#elif TIMER1_SET_OC1A_OR_OC1B_PIN_MODE ==  TIMER1_OC1A_OR_OC1B_PIN_TOGGLE
	   SET_BIT(TCCR1A,4);
	   CLR_BIT(TCCR1A,5);
#elif TIMER1_SET_OC1A_OR_OC1B_PIN_MODE ==  TIMER1_OC1A_OR_OC1B_PIN_CLR
	   CLR_BIT(TCCR1A,4);
	   SET_BIT(TCCR1A,5);
#elif TIMER1_SET_OC1A_OR_OC1B_PIN_MODE ==  TIMER1_OC1A_OR_OC1B_PIN_SET
	   SET_BIT(TCCR1A,4);
	   SET_BIT(TCCR1A,5);
#else
#error "TIMER1 CTC OC1B Mode is not valid.. "
#endif
#else
#error "TIMER1 Channel Mode is not valid.. "
#endif


#elif TIMER1_SET_MODE == TIMER1_PWM_PHASE_AND_FREQUANCY_CORRECT_WITH_OCR1A
	  SET_BIT(TCCR1A,0);
	  CLR_BIT(TCCR1A,1);
	  CLR_BIT(TCCR1B,3);
	  SET_BIT(TCCR1B,4);
#if CHANNEL_MODE == CHANNELA
#if TIMER1_SET_OC1A_OR_OC1B_PIN_MODE == TIMER1_OC1A_OR_OC1B_PIN_DISCONNECTED
	   CLR_BIT(TCCR1A,6);
	   CLR_BIT(TCCR1A,7);
#elif TIMER1_SET_OC1A_OR_OC1B_PIN_MODE ==  TIMER1_OC1A_OR_OC1B_PIN_TOGGLE
	   SET_BIT(TCCR1A,6);
	   CLR_BIT(TCCR1A,7);
#elif TIMER1_SET_OC1A_OR_OC1B_PIN_MODE ==  TIMER1_OC1A_OR_OC1B_PIN_CLR
	   CLR_BIT(TCCR1A,6);
	   SET_BIT(TCCR1A,7);
#elif TIMER1_SET_OC1A_OR_OC1B_PIN_MODE ==  TIMER1_OC1A_OR_OC1B_PIN_SET
	   SET_BIT(TCCR1A,6);
	   SET_BIT(TCCR1A,7);
#else
#error "TIMER1 CTC OC1A Mode is not valid.. "
#endif
#elif CHANNEL_MODE == CHANNELB
#if TIMER1_SET_OC1A_OR_OC1B_PIN_MODE == TIMER1_OC1A_OR_OC1B_PIN_DISCONNECTED
	   CLR_BIT(TCCR1A,4);
	   CLR_BIT(TCCR1A,5);
#elif TIMER1_SET_OC1A_OR_OC1B_PIN_MODE ==  TIMER1_OC1A_OR_OC1B_PIN_TOGGLE
	   SET_BIT(TCCR1A,4);
	   CLR_BIT(TCCR1A,5);
#elif TIMER1_SET_OC1A_OR_OC1B_PIN_MODE ==  TIMER1_OC1A_OR_OC1B_PIN_CLR
	   CLR_BIT(TCCR1A,4);
	   SET_BIT(TCCR1A,5);
#elif TIMER1_SET_OC1A_OR_OC1B_PIN_MODE ==  TIMER1_OC1A_OR_OC1B_PIN_SET
	   SET_BIT(TCCR1A,4);
	   SET_BIT(TCCR1A,5);
#else
#error "TIMER1 CTC OC1B Mode is not valid.. "
#endif
#else
#error "TIMER1 Channel Mode is not valid.. "
#endif
#elif TIMER1_SET_MODE == TIMER1_PHASECORRECT_PWM_MODE_WITH_ICR1
	  CLR_BIT(TCCR1A,0);
	  SET_BIT(TCCR1A,1);
	  CLR_BIT(TCCR1B,3);
	  SET_BIT(TCCR1B,4);
#if CHANNEL_MODE == CHANNELA
#if TIMER1_SET_OC1A_OR_OC1B_PIN_MODE == TIMER1_OC1A_OR_OC1B_PIN_DISCONNECTED
	   CLR_BIT(TCCR1A,6);
	   CLR_BIT(TCCR1A,7);
#elif TIMER1_SET_OC1A_OR_OC1B_PIN_MODE ==  TIMER1_OC1A_OR_OC1B_PIN_TOGGLE
	   SET_BIT(TCCR1A,6);
	   CLR_BIT(TCCR1A,7);
#elif TIMER1_SET_OC1A_OR_OC1B_PIN_MODE ==  TIMER1_OC1A_OR_OC1B_PIN_CLR
	   CLR_BIT(TCCR1A,6);
	   SET_BIT(TCCR1A,7);
#elif TIMER1_SET_OC1A_OR_OC1B_PIN_MODE ==  TIMER1_OC1A_OR_OC1B_PIN_SET
	   SET_BIT(TCCR1A,6);
	   SET_BIT(TCCR1A,7);
#else
#error "TIMER1 CTC OC1A Mode is not valid.. "
#endif
#elif CHANNEL_MODE == CHANNELB
#if TIMER1_SET_OC1A_OR_OC1B_PIN_MODE == TIMER1_OC1A_OR_OC1B_PIN_DISCONNECTED
	   CLR_BIT(TCCR1A,4);
	   CLR_BIT(TCCR1A,5);
#elif TIMER1_SET_OC1A_OR_OC1B_PIN_MODE ==  TIMER1_OC1A_OR_OC1B_PIN_TOGGLE
	   SET_BIT(TCCR1A,4);
	   CLR_BIT(TCCR1A,5);
#elif TIMER1_SET_OC1A_OR_OC1B_PIN_MODE ==  TIMER1_OC1A_OR_OC1B_PIN_CLR
	   CLR_BIT(TCCR1A,4);
	   SET_BIT(TCCR1A,5);
#elif TIMER1_SET_OC1A_OR_OC1B_PIN_MODE ==  TIMER1_OC1A_OR_OC1B_PIN_SET
	   SET_BIT(TCCR1A,4);
	   SET_BIT(TCCR1A,5);
#else
#error "TIMER1 CTC OC1B Mode is not valid.. "
#endif
#else
#error "TIMER1 Channel Mode is not valid.. "
#endif
#elif TIMER1_SET_MODE == TIMER1_PHASECORRECT_PWM_MODE_WITH_OCR1A
	  SET_BIT(TCCR1A,0);
	  SET_BIT(TCCR1A,1);
	  CLR_BIT(TCCR1B,3);
	  SET_BIT(TCCR1B,4);
#if CHANNEL_MODE == CHANNELA
#if TIMER1_SET_OC1A_OR_OC1B_PIN_MODE == TIMER1_OC1A_OR_OC1B_PIN_DISCONNECTED
	   CLR_BIT(TCCR1A,6);
	   CLR_BIT(TCCR1A,7);
#elif TIMER1_SET_OC1A_OR_OC1B_PIN_MODE ==  TIMER1_OC1A_OR_OC1B_PIN_TOGGLE
	   SET_BIT(TCCR1A,6);
	   CLR_BIT(TCCR1A,7);
#elif TIMER1_SET_OC1A_OR_OC1B_PIN_MODE ==  TIMER1_OC1A_OR_OC1B_PIN_CLR
	   CLR_BIT(TCCR1A,6);
	   SET_BIT(TCCR1A,7);
#elif TIMER1_SET_OC1A_OR_OC1B_PIN_MODE ==  TIMER1_OC1A_OR_OC1B_PIN_SET
	   SET_BIT(TCCR1A,6);
	   SET_BIT(TCCR1A,7);
#else
#error "TIMER1 CTC OC1A Mode is not valid.. "
#endif
#elif CHANNEL_MODE == CHANNELB
#if TIMER1_SET_OC1A_OR_OC1B_PIN_MODE == TIMER1_OC1A_OR_OC1B_PIN_DISCONNECTED
	   CLR_BIT(TCCR1A,4);
	   CLR_BIT(TCCR1A,5);
#elif TIMER1_SET_OC1A_OR_OC1B_PIN_MODE ==  TIMER1_OC1A_OR_OC1B_PIN_TOGGLE
	   SET_BIT(TCCR1A,4);
	   CLR_BIT(TCCR1A,5);
#elif TIMER1_SET_OC1A_OR_OC1B_PIN_MODE ==  TIMER1_OC1A_OR_OC1B_PIN_CLR
	   CLR_BIT(TCCR1A,4);
	   SET_BIT(TCCR1A,5);
#elif TIMER1_SET_OC1A_OR_OC1B_PIN_MODE ==  TIMER1_OC1A_OR_OC1B_PIN_SET
	   SET_BIT(TCCR1A,4);
	   SET_BIT(TCCR1A,5);
#else
#error "TIMER1 CTC OC1B Mode is not valid.. "
#endif
#else
#error "TIMER1 Channel Mode is not valid.. "
#endif
#elif  TIMER1_SET_MODE == TIMER1_CTC_MODE_WITH_ICR1
	   CLR_BIT(TCCR1A,0);
	   CLR_BIT(TCCR1A,1);
	   SET_BIT(TCCR1B,3);
	   SET_BIT(TCCR1B,4);
#if CHANNEL_MODE == CHANNELA
#if TIMER1_SET_CTC_INTERRUPT == TIMER1_CTC_INTERRUPT_ENABLED
	SET_BIT(TIMSK,4);
#elif TIMER1_SET_CTC_INTERRUPT == TIMER1_CTC_INTERRUPT_DISABLED
	CLR_BIT(TIMSK,4);
#else
#error "TIMER1 CTC Interrupt Mode is not valid..."
#endif
#if TIMER1_SET_OC1A_OR_OC1B_PIN_MODE == TIMER1_OC1A_OR_OC1B_PIN_DISCONNECTED
	   CLR_BIT(TCCR1A,6);
	   CLR_BIT(TCCR1A,7);
#elif TIMER1_SET_OC1A_OR_OC1B_PIN_MODE ==  TIMER1_OC1A_OR_OC1B_PIN_TOGGLE
	   SET_BIT(TCCR1A,6);
	   CLR_BIT(TCCR1A,7);
#elif TIMER1_SET_OC1A_OR_OC1B_PIN_MODE ==  TIMER1_OC1A_OR_OC1B_PIN_CLR
	   CLR_BIT(TCCR1A,6);
	   SET_BIT(TCCR1A,7);
#elif TIMER1_SET_OC1A_OR_OC1B_PIN_MODE ==  TIMER1_OC1A_OR_OC1B_PIN_SET
	   SET_BIT(TCCR1A,6);
	   SET_BIT(TCCR1A,7);
#else
#error "TIMER1 CTC OC1A Mode is not valid.. "
#endif
#elif CHANNEL_MODE == CHANNELB
#if TIMER1_SET_CTC_INTERRUPT == TIMER1_CTC_INTERRUPT_ENABLED
	SET_BIT(TIMSK,3);
#elif TIMER1_SET_CTC_INTERRUPT == TIMER1_CTC_INTERRUPT_DISABLED
	CLR_BIT(TIMSK,3);
#else
#error "TIMER1 CTC Interrupt Mode is not valid..."
#endif
#if TIMER1_SET_OC1A_OR_OC1B_PIN_MODE == TIMER1_OC1A_OR_OC1B_PIN_DISCONNECTED
	   CLR_BIT(TCCR1A,4);
	   CLR_BIT(TCCR1A,5);
#elif TIMER1_SET_OC1A_OR_OC1B_PIN_MODE ==  TIMER1_OC1A_OR_OC1B_PIN_TOGGLE
	   SET_BIT(TCCR1A,4);
	   CLR_BIT(TCCR1A,5);
#elif TIMER1_SET_OC1A_OR_OC1B_PIN_MODE ==  TIMER1_OC1A_OR_OC1B_PIN_CLR
	   CLR_BIT(TCCR1A,4);
	   SET_BIT(TCCR1A,5);
#elif TIMER1_SET_OC1A_OR_OC1B_PIN_MODE ==  TIMER1_OC1A_OR_OC1B_PIN_SET
	   SET_BIT(TCCR1A,4);
	   SET_BIT(TCCR1A,5);
#else
#error "TIMER1 CTC OC1B Mode is not valid.. "
#endif
#else
#error "TIMER1 Channel Mode is not valid.. "
#endif
#elif  TIMER1_SET_MODE == TIMER1_FAST_PWM_MODE_WITH_ICR1
	    SET_BIT(TCCR1B,4);
	   	SET_BIT(TCCR1B,3);
	   	SET_BIT(TCCR1A,1);
	   	CLR_BIT(TCCR1A,0);
#if CHANNEL_MODE == CHANNELA
#if TIMER1_SET_OC1A_OR_OC1B_PIN_MODE == TIMER1_OC1A_OR_OC1B_PIN_DISCONNECTED
	   CLR_BIT(TCCR1A,6);
	   CLR_BIT(TCCR1A,7);
#elif TIMER1_SET_OC1A_OR_OC1B_PIN_MODE ==  TIMER1_OC1A_OR_OC1B_PIN_TOGGLE
	   SET_BIT(TCCR1A,6);
	   CLR_BIT(TCCR1A,7);
#elif TIMER1_SET_OC1A_OR_OC1B_PIN_MODE ==  TIMER1_OC1A_OR_OC1B_PIN_CLR
	   CLR_BIT(TCCR1A,6);
	   SET_BIT(TCCR1A,7);
#elif TIMER1_SET_OC1A_OR_OC1B_PIN_MODE ==  TIMER1_OC1A_OR_OC1B_PIN_SET
	   SET_BIT(TCCR1A,6);
	   SET_BIT(TCCR1A,7);
#else
#error "TIMER1 CTC OC1A Mode is not valid.. "
#endif
#elif CHANNEL_MODE == CHANNELB
#if TIMER1_SET_OC1A_OR_OC1B_PIN_MODE == TIMER1_OC1A_OR_OC1B_PIN_DISCONNECTED
	   CLR_BIT(TCCR1A,4);
	   CLR_BIT(TCCR1A,5);
#elif TIMER1_SET_OC1A_OR_OC1B_PIN_MODE ==  TIMER1_OC1A_OR_OC1B_PIN_TOGGLE
	   SET_BIT(TCCR1A,4);
	   CLR_BIT(TCCR1A,5);
#elif TIMER1_SET_OC1A_OR_OC1B_PIN_MODE ==  TIMER1_OC1A_OR_OC1B_PIN_CLR
	   CLR_BIT(TCCR1A,4);
	   SET_BIT(TCCR1A,5);
#elif TIMER1_SET_OC1A_OR_OC1B_PIN_MODE ==  TIMER1_OC1A_OR_OC1B_PIN_SET
	   SET_BIT(TCCR1A,4);
	   SET_BIT(TCCR1A,5);
#else
#error "TIMER1 CTC OC1B Mode is not valid.. "
#endif
#else
#error "TIMER1 Channel Mode is not valid.. "
#endif
#elif  TIMER1_SET_MODE == TIMER1_FAST_PWM_MODE_WITH_OCR1A
	   SET_BIT(TCCR1A,0);
	   SET_BIT(TCCR1A,1);
	   SET_BIT(TCCR1B,3);
	   SET_BIT(TCCR1B,4);
#if CHANNEL_MODE == CHANNELA
#if TIMER1_SET_OC1A_OR_OC1B_PIN_MODE == TIMER1_OC1A_OR_OC1B_PIN_DISCONNECTED
	   CLR_BIT(TCCR1A,6);
	   CLR_BIT(TCCR1A,7);
#elif TIMER1_SET_OC1A_OR_OC1B_PIN_MODE ==  TIMER1_OC1A_OR_OC1B_PIN_TOGGLE
	   SET_BIT(TCCR1A,6);
	   CLR_BIT(TCCR1A,7);
#elif TIMER1_SET_OC1A_OR_OC1B_PIN_MODE ==  TIMER1_OC1A_OR_OC1B_PIN_CLR
	   CLR_BIT(TCCR1A,6);
	   SET_BIT(TCCR1A,7);
#elif TIMER1_SET_OC1A_OR_OC1B_PIN_MODE ==  TIMER1_OC1A_OR_OC1B_PIN_SET
	   SET_BIT(TCCR1A,6);
	   SET_BIT(TCCR1A,7);
#else
#error "TIMER1 CTC OC1A Mode is not valid.. "
#endif
#elif CHANNEL_MODE == CHANNELB
#if TIMER1_SET_OC1A_OR_OC1B_PIN_MODE == TIMER1_OC1A_OR_OC1B_PIN_DISCONNECTED
	   CLR_BIT(TCCR1A,4);
	   CLR_BIT(TCCR1A,5);
#elif TIMER1_SET_OC1A_OR_OC1B_PIN_MODE ==  TIMER1_OC1A_OR_OC1B_PIN_TOGGLE
	   SET_BIT(TCCR1A,4);
	   CLR_BIT(TCCR1A,5);
#elif TIMER1_SET_OC1A_OR_OC1B_PIN_MODE ==  TIMER1_OC1A_OR_OC1B_PIN_CLR
	   CLR_BIT(TCCR1A,4);
	   SET_BIT(TCCR1A,5);
#elif TIMER1_SET_OC1A_OR_OC1B_PIN_MODE ==  TIMER1_OC1A_OR_OC1B_PIN_SET
	   SET_BIT(TCCR1A,4);
	   SET_BIT(TCCR1A,5);
#else
#error "TIMER1 CTC OC1B Mode is not valid.. "
#endif
#else
#error "TIMER1 Channel Mode is not valid.. "
#endif
#else
#error "TIMER1 Mode is not valid..."
#endif

}
/*Set Preload Function*/
void TIMER1_VidSetPreload(u16 Copy_u16Preload)
{
	TCNT1=Copy_u16Preload;
}
void TIMER1_VidSetTopValue(u16 Copy_u16TopValue)
{
	ICR1 = Copy_u16TopValue;

}
void TIMER1_VidSetCTCValueCHA(u16 Copy_u16CTCValue)
{
	OCR1A =  Copy_u16CTCValue;

}
void TIMER1_VidSetCTCValueCHB(u16 Copy_u16CTCValue)
{
	OCR1B =  Copy_u16CTCValue;

}


void TIMER1_VidICUInit(void)
{
#if ICU_Edge_Select == RISING_EDGE
	/*ICU Edge Select-->Rising edge*/
	SET_BIT(TCCR1B,6);
	/*TIMER OVERFLOW INTERRUPT ENABLLED*/
	SET_BIT(TIMSK,2);
	/*ICU INTERRUPT ENABLLED*/
	SET_BIT(TIMSK,5);
#elif ICU_Edge_Select == FALLING_EDGE
	/*ICU Edge Select-->Falling edge*/
	CLR_BIT(TCCR1B,6);
	/*TIMER OVERFLOW INTERRUPT ENABLLED*/
	SET_BIT(TIMSK,2);
	/*ICU INTERRUPT ENABLLED*/
	SET_BIT(TIMSK,5);
#else
#error"ICU Edge Select is not valid...."
#endif
}
/* TIMER1 OVF */
void __vector_9(void)   __attribute__((signal));
void __vector_9(void)
{
	Count++;
}
/* TIMER1 CAPT */
void __vector_6(void)   __attribute__((signal));
void __vector_6(void)
{
	if(Flag==0)
		{
			T1=ICR1+Count*65536;
			/*ICU Sense with falling*/
			CLR_BIT(TCCR1B,6);
			Flag=1;
		}
		else if(Flag==1)
		{
			T2=ICR1+Count*65536;
			/*ICU Sense with Rising*/
			SET_BIT(TCCR1B,6);
			Flag=2;
		}
		else if(Flag==2)
		{
			T3=ICR1+Count*65536;
			Flag=3;
		}
}

void TIMER1_VidOVF_SetCallBack(void(*Copy_VidCallBack)(void))
{
	TIMER1_CallBack=Copy_VidCallBack;
}

void TIMER1_VidCTC_SetCallBack(void(*Copy_VidCallBack)(void))
{
	TIMER1_CallBack=Copy_VidCallBack;
}
/* TIMER1 COMPA */
void __vector_7(void)   __attribute__((signal));
void __vector_7(void)
{
	TIMER1_CallBack();
}
/*  TIMER1 COMPB */
void __vector_8(void)   __attribute__((signal));
void __vector_8(void)
{
	TIMER1_CallBack();
}
void TIMER1_VidCompute_Freq_And_Duty(u32 *Copy_u32Freq,u8 *Copy_u8DutyCycle)
{
	if(Flag==3)
	{
		*Copy_u32Freq = (1000000/(T3-T1));
		*Copy_u8DutyCycle = ((T2-T1)*100)/(T3-T1);
		Flag=4;
	}

}
void TIMER2_VidInit(void)
{
	/*Select the suitable Prescaler */
		TCCR2&=0xF8;
		TCCR2|=TIMER2_SET_PRESCALER;
		/*Mode Select*/
	#if TIMER2_SET_MODE == TIMER2_NORMAL_MODE
		CLR_BIT(TCCR2,6);
		CLR_BIT(TCCR2,3);
		/*Timer Overflow Interrupt Enable*/
		SET_BIT(TIMSK,6);

	#elif TIMER2_SET_MODE == TIMER2_CTC_MODE
		CLR_BIT(TCCR2,6);
		SET_BIT(TCCR2,3);
	#if TIMER2_SET_CTC_INTERRUPT == TIMER2_CTC_INTERRUPT_ENABLED
		SET_BIT(TIMSK,7);
	#elif TIMER2_SET_CTC_INTERRUPT == TIMER2_CTC_INTERRUPT_DISABLED
		CLR_BIT(TIMSK,7);
	#else
	#error "TIMER2 CTC Interrupt Mode is not valid..."
	#endif
	#if TIMER2_SET_OC0_PIN_MODE == TIMER2_OC2_PIN_DISCONNECTED
		CLR_BIT(TCCR2,5);
		CLR_BIT(TCCR2,4);
	#elif TIMER2_SET_OC2_PIN_MODE == TIMER0_OC2_PIN_TOGGLE
		CLR_BIT(TCCR2,5);
		SET_BIT(TCCR2,4);
	#elif TIMER2_SET_OC2_PIN_MODE == TIMER2_OC2_PIN_SET
		SET_BIT(TCCR2,5);
		SET_BIT(TCCR2,4);
	#elif TIMER2_SET_OC2_PIN_MODE == TIMER2_OC2_PIN_CLR
		SET_BIT(TCCR2,5);
		CLR_BIT(TCCR2,4);
	#else
	#error "TIMER2 CTC OC2 Mode is not valid..."
	#endif
	#elif TIMER2_SET_MODE == TIMER2_PHASECORRECT_PWM_MODE
		SET_BIT(TCCR2,6);
		CLR_BIT(TCCR2,3);
		/*select phase correct mode */
	#if TIMER2_SET_PWM_MODE == TIMER2_NUN_INVERTING_PWM
		   SET_BIT(TCCR2,1);
			CLR_BIT(TCCR2,0);
			CLR_BIT(TCCR2,4);
			SET_BIT(TCCR2,5);

	#elif TIMER2_SET_PWM_MODE == TIMER2_INVERTING_PWM
		    SET_BIT(TCCR2,5);
			SET_BIT(TCCR2,4);

	#else
	#error "TIMER2 PWM Mode is not valid..."
	#endif
	#elif TIMER2_SET_MODE == TIMER2_FAST_PWM_MODE
		SET_BIT(TCCR2,6);
		SET_BIT(TCCR2,3);
		/*select TIMER2 FAST PWM_MODE mode */
	#if TIMER2_SET_PWM_MODE == TIMER2_NUN_INVERTING_PWM
		        SET_BIT(TCCR2,1);
				CLR_BIT(TCCR2,0);
				CLR_BIT(TCCR2,4);
				SET_BIT(TCCR2,5);
	#elif TIMER2_SET_PWM_MODE == TIMER2_INVERTING_PWM
				SET_BIT(TCCR2,5);
				SET_BIT(TCCR2,4);


	#else
	#error "TIMER2 PWM Mode is not valid..."
	#endif
	#else
	#error "TIMER2 Mode is not valid..."
	#endif



}
/*Set Preload Function*/
void TIMER2_VidSetPreload(u8 Copy_u8Preload)
{
	TCNT2=Copy_u8Preload;
}
/*Set CTC Value Function*/
void TIMER2_VidSetCTCValue(u8 Copy_u8CTCValue)
{
	OCR2=Copy_u8CTCValue;
}
void TIMER2_VidOVF_SetCallBack(void(*Copy_VidCallBack)(void))
{
	TIMER2_CallBack=Copy_VidCallBack;
}
void TIMER2_VidCTC_SetCallBack(void(*Copy_VidCallBack)(void))
{
	TIMER2_CallBack=Copy_VidCallBack;
}
void __vector_4(void)   __attribute__((signal));
void __vector_4(void)
{
	TIMER2_CallBack();
}
/*timer2 OV*/
void __vector_5(void)   __attribute__((signal));
void __vector_5(void)
{
	TIMER2_CallBack();
}
