/*
 * MADC_Config.h
 *
 *  Created on: Nov 22, 2021
 *      Author: gerges
 */

#ifndef MCAL_MADC_MADC_CONFIG_H_
#define MCAL_MADC_MADC_CONFIG_H_

/*MADC REFERENCE VOLATGE Options:
 *1- MADC_AVCC_REFERENCEVOLATGE
 *2- MADC_2.56V_REFERENCEVOLATGE
 */

#define MADC_SET_REFERENCEVOLATGE  MADC_AVCC_REFERENCEVOLATGE

/*MADC Prescaler options:
 * 1- MADC_2_PRESCALER
 * 2- MADC_4_PRESCALER
 * 3- MADC_8_PRESCALER
 * 4- MADC_16_PRESCALER
 * 5- MADC_32_PRESCALER
 * 6- MADC_64_PRESCALER
 * 7- MADC_128_PRESCALER
 */
#define MADC_SET_PRESCALER   MADC_8_PRESCALER

/*MADC Adjust Options:
 *1- MADC_LEFT_ADJUST
 *2- MADC_RIGHT_ADJUST
 */

#define MADC_SET_ADJUST  MADC_RIGHT_ADJUST

/*		ADC Auto Trigger Source	Options
 * 1-	MADC_FREE_RUNING_TRIGGER_SOURCE
 * 2-	MADC_ANALOG_COMPARATOR_TRIGGER_SOURCE
 * 3-	MADC_EXTI_TRIGGER_SOURCE
 * 4-	MADC_TIMER0_COMRARE_MATCH_TRIGGER_SOURCE
 * 5-	MADC_TIMER0_OVERFLOW_TRIGGER_SOURCE
 * 6-	MADC_TIMER0_COMRARE_MATCH_B_TRIGGER_SOURCE
 * 7-	MADC_TIMER1_OVERFLOW_TRIGGER_SOURCE
 * 8-	MADC_TIMER1_CAPTURE_EVENT_TRIGGER_SOURCE
 */
#define MADC_SET_TRIGGER_SOURCE		MADC_EXTI_TRIGGER_SOURCE

#endif /* MCAL_MADC_MADC_CONFIG_H_ */
